### ISSUE TITLE
Was the base config created by the wizard?

### ISSUE THREAD

**Issue by aioue** [LeePorte/edgerouter-zen-config#1]
If so, what version of the FW were you running?

**Comment by LeePorte** [comment]
It wasn't a wizard config. I'm not actually sure of the version though it was definitely on the 1.x series. I've definitely had it running on 1.10.2 according to https://github.com/LeePorte/edgerouter-zen-config/commit/29f43ac571d3f3390dcb0a4b5a05becc0322f627

I'm now on 2.0.8-hotfix.1

Are you running into any issues?

**Comment by aioue** [comment]
Think I was looking at PPPoE together with UPNP rules, which I [resolved over here](https://gist.github.com/plembo/c7f596ce6e690c6c022a6153c674f471?permalink_comment_id=3881081#gistcomment-3881081).
